name: Publish to npm

# Temporarily disabled while package is in development mode
# Remove the 'on: {}' line and uncomment the section below when ready to publish
on: {}
# on:
#   release:
#     types: [created]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build package
        run: npm run build
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release Summary
        run: |
          echo "✅ Successfully published ${{ github.event.release.tag_name }} to npm!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📦 Package: editium" >> $GITHUB_STEP_SUMMARY
          echo "🔖 Version: ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "🔗 npm: https://www.npmjs.com/package/editium" >> $GITHUB_STEP_SUMMARY
